### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by swimmie0** [kucc/kuflix-client#8]
### 채린 TODO
- [ ] 리뷰작성 페이지, 명대사 작성 페이지 (ing)
- [ ] 햄버거메뉴  사이드바 
- (시간되면) 마이페이지 api 연동

### 수영 TODO
> 9월부터 열일예정..😂
- [ ] 검색페이지 : 페이지네이션 or 무한스크롤
- [ ] 메인페이지 api 완성시 연동
- [ ] 인라인 사용자 정보 수정
- [ ] 상태관리 고민
  - react-query staleTime 등 조정
  - redux? recoil 공부해서 써보기?

### More
- 실제 api 서버 연결 후 CRUD 테스트 필요
- ui 보완에 따른 추가 기능/페이지 연동
  - 삭제, 찜한영화 페이지 등
  - [ui 디자인](https://www.figma.com/file/EGHDF4vKyprXTvU9fB4FMa/Untitled?node-id=0%3A1)
